const videos = [
  {
    id: 'qqMOyMe81C4',
    time: '2:44',
    thumbnail: '../../../assets/connection-heals.jpeg',
    slug: 'hogyan-gyogyit-a-kapcsolat',
  },
  {
    id: '0HirACmTzEU',
    time: '5:27',
    thumbnail: '../../../assets/authentic.jpeg',
    slug: 'az-autentikus-kapcsolodas',
  },
  {
    id: '5YtDDUbfy0w',
    time: '5:00',
    thumbnail: '../../../assets/connection.jpg',
    title: 'A kapcsolódás művészete',
    slug: 'a-kapcsolodas-muveszete',
  },
  {
    id: 'EH-ZXVkXrdY',
    time: '8:37',
    thumbnail: '../../../assets/happiness.jpg',
    title: 'A boldogság útja',
    slug: 'a-boldogsag-utja',
  },
  {
    id: '2Lil2rhmiIM',
    time: '7:14',
    thumbnail: '../../../assets/fatigue.jpg',
    title: 'A fáradtság okai',
    slug: 'a-faradtsag-okai',
  },
  {
    id: 'HNX9vnl1y7w',
    time: '9:47',
    thumbnail: '../../../assets/mindreader.jpg',
    title: 'Gondolatolvasás a párkapcsolatban',
    slug: 'gondolatolvasas-a-parkapcsolatban',
  },
  {
    id: 'aYkUC2N5doU',
    time: '4:40',
    thumbnail: '../../../assets/problem.jpg',
    title: 'A problémák gyökere',
    slug: 'a-problemak-gyokere',
  },
  {
    id: '9YuVg3Rifxo',
    time: '15:44',
    thumbnail: '../../../assets/economy.jpg',
    title: 'Gazdasági válság és lelki egészség',
    slug: 'gazdasagi-valsag-es-lelki-egeszseg',
  },
  {
    id: 'AhT75A_XK1w',
    time: '6:13',
    thumbnail: '../../../assets/meditation.jpg',
    title: 'A meditáció ereje',
    slug: 'a-meditacio-ereje',
  },
  {
    id: 'sDet47yXFAY',
    time: '7:16',
    thumbnail: '../../../assets/develop.jpg',
    title: 'Személyiségfejlődés útjai',
    slug: 'szemelyisegfejlodes-utjai',
  },
  {
    id: 'WiKfvTJEuzk',
    time: '43:51',
    thumbnail: '../../../assets/interview.jpg',
    title: 'Interjú a terápiáról',
    slug: 'interju-a-terapiarol',
  },
  {
    id: 'SM92eIvOyMU',
    time: '6:20',
    thumbnail: '../../../assets/woman.jpg',
    title: 'A nőiesség ereje',
    slug: 'a-noiesseg-ereje',
  },
  {
    id: 'jWxa49ra4yU',
    time: '6:44',
    thumbnail: '../../../assets/pillars.jpg',
    title: 'A kapcsolat pillérei',
    slug: 'a-kapcsolat-pillerei',
  },
  {
    id: 'vyDJY6Izqqw',
    time: '3:39',
    thumbnail: '../../../assets/healing.jpg',
    title: 'A gyógyulás útja',
    slug: 'a-gyogyulas-utja',
  },
  {
    id: 'M7MkCiS62dU',
    time: '7:04',
    thumbnail: '../../../assets/balance.jpg',
    title: 'Az egyensúly megteremtése',
    slug: 'az-egyensuly-megteremtese',
  },
  {
    id: 'sdHu2uEiwpA',
    time: '6:16',
    thumbnail: '../../../assets/uncertainty.jpg',
    title: 'A bizonytalanság kezelése',
    slug: 'a-bizonytalansag-kezelese',
  },
  {
    id: 'WPrHUFwm4GE',
    time: '6:55',
    thumbnail: '../../../assets/trust.jpg',
    title: 'A bizalom építése',
    slug: 'a-bizalom-epitese',
  },
  {
    id: 'e9-R6oMKO5M',
    time: '4:44',
    thumbnail: '../../../assets/help.jpg',
    title: 'Hogyan segítsünk másoknak?',
    slug: 'hogyan-segitsunk-masoknak',
  },
  {
    id: '3mZM3u8p7Vk',
    time: '3:12',
    thumbnail: '../../../assets/expectation.jpg',
    title: 'Az elvárások csapdája',
    slug: 'az-elvarasok-csapdaja',
  },
  {
    id: 'UYsE9aGTjuA',
    time: '9:56',
    thumbnail: '../../../assets/states.jpg',
    title: 'Tudatállapotok változása',
    slug: 'tudatallapotok-valtozasa',
  },
  {
    id: '-NW4YIfzxHk',
    time: '3:51',
    thumbnail: '../../../assets/gitta.jpg',
    title: 'Beszélgetés Gittával',
    slug: 'beszelgetes-gittaval',
  },
  {
    id: 'mi8ks_F0TiA',
    time: '4:14',
    thumbnail: '../../../assets/base.jpg',
    title: 'Az alap megteremtése',
    slug: 'az-alap-megteremtese',
  },
  {
    id: 'VS5ASyFswGM',
    time: '4:55',
    thumbnail: '../../../assets/breakdown.jpg',
    title: 'A kapcsolat megszakadása',
    slug: 'a-kapcsolat-megszakadasa',
  },
  {
    id: 'hypSiM_crLs',
    time: '3:15',
    thumbnail: '../../../assets/cancer.jpg',
    title: 'Daganatos betegségek lelki háttere',
    slug: 'daganatos-betegsegek-lelki-hattere',
  },
  {
    id: '_5Yl6iu9l4g',
    time: '3:13',
    thumbnail: '../../../assets/acceptance.jpg',
    title: 'Az elfogadás művészete',
    slug: 'az-elfogadas-muveszete',
  },
  {
    id: 'LteXgIwV3vo',
    time: '3:52',
    thumbnail: '../../../assets/heart.jpg',
    title: 'A szív bölcsessége',
    slug: 'a-sziv-bolcsessege',
  },
  {
    id: 'tj6K72L3J_U',
    time: '2:54',
    thumbnail: '../../../assets/trap.jpg',
    title: 'A csapdák felismerése',
    slug: 'a-csapdak-felismerese',
  },
  {
    id: 'pVJFjWSB_as',
    time: '2:55',
    thumbnail: '../../../assets/bridge.jpg',
    title: 'Híd a kapcsolatokban',
    slug: 'hid-a-kapcsolatokban',
  },
];

export default videos;
