const videos = [
  {
    id: 'qqMOyMe81C4',
    time: '2:44',
    thumbnail: '../../../assets/connection-heals.jpeg',
    slug: 'hogyan-gyogyit-a-kapcsolat',
  },
  {
    id: '0HirACmTzEU',
    time: '5:27',
    thumbnail: '../../../assets/authentic.jpeg',
    slug: 'lehetseges-onazonosan-kapcsolodni',
  },
  {
    id: '5YtDDUbfy0w',
    time: '5:00',
    thumbnail: '../../../assets/connection.jpg',
    slug: 'a-kapcsolodas-mindenekfelett',
  },
  {
    id: 'EH-ZXVkXrdY',
    time: '8:37',
    thumbnail: '../../../assets/happiness.jpg',
    slug: 'a-boldogsag-nyomaban',
  },
  {
    id: '2Lil2rhmiIM',
    time: '7:14',
    thumbnail: '../../../assets/fatigue.jpg',
    slug: 'fasultsag-a-parkapcsolatban',
  },
  {
    id: 'HNX9vnl1y7w',
    time: '9:47',
    thumbnail: '../../../assets/mindreader.jpg',
    slug: 'a-ferfi-nem-gondolatolvaso',
  },
  {
    id: 'aYkUC2N5doU',
    time: '4:40',
    thumbnail: '../../../assets/problem.jpg',
    slug: 'hogyan-kezdd-el-megoldani-a-problemadat',
  },
  {
    id: '9YuVg3Rifxo',
    time: '15:44',
    thumbnail: '../../../assets/economy.jpg',
    slug: 'a-gazdasagi-helyzet-hatasa-testi-lelki-egeszsegedre',
  },
  {
    id: 'AhT75A_XK1w',
    time: '6:13',
    thumbnail: '../../../assets/meditation.jpg',
    slug: 'nem-kell-mindenkinek-meditalnia',
  },
  {
    id: 'sDet47yXFAY',
    time: '7:16',
    thumbnail: '../../../assets/develop.jpg',
    slug: 'ferfi-fejlodj-a-parkapcsolatodert',
  },
  {
    id: 'WiKfvTJEuzk',
    time: '43:51',
    thumbnail: '../../../assets/interview.jpg',
    slug: 'rezgesek-interju-lucien-del-marral',
  },
  {
    id: 'SM92eIvOyMU',
    time: '6:20',
    thumbnail: '../../../assets/woman.jpg',
    slug: 'no-az-erejeben',
  },
  {
    id: 'jWxa49ra4yU',
    time: '6:44',
    thumbnail: '../../../assets/pillars.jpg',
    slug: 'az-oromteli-parkapcsolat-harom-alappillere',
  },
  {
    id: 'vyDJY6Izqqw',
    time: '3:39',
    thumbnail: '../../../assets/healing.jpg',
    slug: 'mikor-fogok-mar-meggyogyulni',
  },
  {
    id: 'M7MkCiS62dU',
    time: '7:04',
    thumbnail: '../../../assets/balance.jpg',
    slug: 'uj-egyensuly-a-betegsegben',
  },
  {
    id: 'sdHu2uEiwpA',
    time: '6:16',
    thumbnail: '../../../assets/uncertainty.jpg',
    slug: 'oromben-az-elet-alapveto-bizonytalansagaban',
  },
  {
    id: 'WPrHUFwm4GE',
    time: '6:55',
    thumbnail: '../../../assets/trust.jpg',
    slug: 'bizalom-visszaallitasa-a-ferfiak-fele',
  },
  {
    id: 'e9-R6oMKO5M',
    time: '4:44',
    thumbnail: '../../../assets/help.jpg',
    slug: 'segitsegkeres-es-elfogadas',
  },
  {
    id: '3mZM3u8p7Vk',
    time: '3:12',
    thumbnail: '../../../assets/megfeleles.webp',
    slug: 'meg-mindig-probalsz-masoknak-megfelelni',
  },
  {
    id: 'UYsE9aGTjuA',
    time: '9:56',
    thumbnail: '../../../assets/states.jpg',
    slug: 'a-let-harom-allapota',
  },
  {
    id: '-NW4YIfzxHk',
    time: '3:51',
    thumbnail: '../../../assets/gitta.jpg',
    slug: 'lenart-gittaval-sikerrol-es-kitartasrol',
  },
  {
    id: 'mi8ks_F0TiA',
    time: '4:14',
    thumbnail: '../../../assets/base.jpg',
    slug: 'mi-a-parkapcsolatod-alapja',
  },
  {
    id: 'VS5ASyFswGM',
    time: '4:55',
    thumbnail: '../../../assets/breakdown.jpg',
    slug: 'miert-orulj-ha-szetesik-az-eleted',
  },
  {
    id: 'hypSiM_crLs',
    time: '3:15',
    thumbnail: '../../../assets/cancer.jpg',
    slug: 'hogyan-keruld-el-a-rakot',
  },
  {
    id: '_5Yl6iu9l4g',
    time: '3:13',
    thumbnail: '../../../assets/acceptance.jpg',
    slug: 'elfogadas-kontra-beletorodes',
  },
  {
    id: 'LteXgIwV3vo',
    time: '3:52',
    thumbnail: '../../../assets/heart.jpg',
    slug: 'ot-jel-hogy-meg-kellene-gyogyitanod-a-szivedet',
  },
  {
    id: 'tj6K72L3J_U',
    time: '2:54',
    thumbnail: '../../../assets/trap.jpg',
    slug: 'miert-csapda-a-pozitiv-gondolkozas',
  },
  {
    id: 'pVJFjWSB_as',
    time: '2:55',
    thumbnail: '../../../assets/bridge.jpg',
    slug: 'leugrottam-egy-hidrol-tanulsagos-volt',
  },
];

export default videos;
